name: reddit-scan

on:
  push:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Pull dependencies
        run: yarn install

      - name: Run
        run: |
          yarn start:reddit-scan \
            --client-id ${{ secrets.REDDIT_CLIENT_ID }} \
            --client-secret ${{ secrets.REDDIT_CLIENT_SECRET }} \
            --username ${{ secrets.REDDIT_USERNAME }} \
            --password ${{ secrets.REDDIT_PASSWORD }} \
            --sub ukraine \
            --sub ukraina \
            --sub ukrainianconflict \
            --sub ukraineconflict \
            --sub yurop \
            --entry kyiv \
            --entry lviv \
            --entry kharkiv \
            --entry odesa \
            --entry mykolaiv \
            --entry chornobyl \
            --entry irpin
            --entry chernihiv \
            --interval 900 \
            --submission-sampling 1 \
            --comment-sampling 0.75
